version: '3'

services:
  app:
    build:
      context: ../
    command: sleep infinity
    volumes:
      - ../:/code
      - ~/.gitconfig:/root/.gitconfig
      - ~/.ssh:/root/.ssh
    ports:
      - "8000:8000"
